name: Java CI/CD with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn test --file pom.xml

      - name: Code Quality Analysis (Static code analysis)
        run: mvn clean install sonar:sonar -Dsonar.projectKey=MaXimeHH_ProductApp -Dsonar.organization=maxdevorganization -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=4056e09f52a633576e7a7f88b3b6857217551ac5

      - name: Code Quality Check (Linting)
        run: mvn checkstyle:check --file pom.xml

      - name: Code Coverage Analysis
        run: mvn clean test jacoco:report --file pom.xml

      - name: Dependency Security Check
        run: mvn org.owasp:dependency-check-maven:check --file pom.xml
